# Generated by Django 2.2 on 2022-12-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20221209_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_market_price',
            field=models.BigIntegerField(default=1, verbose_name='minimum price'),
            preserve_default=False,
        ),
    ]
