version: "3.8"
services:

#  crawler-link:
#    container_name: crawler-link
#    restart: always
#    image: link-crawler:1.0
#    command: bash -c "python3 runner.py"
#    volumes:
#      - crawler_logger:/var/www/inquiries_logger/logs
#    ports:
#      - "8010:8010"
#    env_file:
#      - crawler-link.env
#    network_mode: "host"

#  crawler-detail:
#    container_name: crawler-detail
#    restart: always
#    image: link-crawler:1.0
#    command: bash -c "python3 runner.py"
#    volumes:
#      - crawler_logger:/var/www/inquiries_logger/logs
#    ports:
#      - "8011:8011"
#    env_file:
#      - crawler-detail.env

  torob:
    container_name: torob
    restart: always
    image: torob:1.0
    command: bash -c "gunicorn torob.wsgi:application --bind 0.0.0.0:8011"
    volumes:
      - torob_logger:/var/www/torob/logs
      - torob_static:/static
    ports:
      - "800:8000"
    env_file:
      - torob.env
    
volumes:
#    crawler_logger:
    torob_logger:
    torob_static:
