# Generated by Django 2.2 on 2022-12-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('price', models.BigIntegerField(verbose_name='price')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
