# Generated by Django 2.2 on 2022-12-09 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20221209_1807'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'shop', 'verbose_name_plural': 'shops'},
        ),
        migrations.AddField(
            model_name='shop',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='product.Product', verbose_name='product'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='shop',
            table='shop',
        ),
    ]
